//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.Edesia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddressControllerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddressControllerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrei15193.Edesia.Resources.AddressControllerStrings", typeof(AddressControllerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă.
        /// </summary>
        public static string AddAddressButton_DisplayName {
            get {
                return ResourceManager.GetString("AddAddressButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adăugare adresă.
        /// </summary>
        public static string AddAddressViewTitle {
            get {
                return ResourceManager.GetString("AddAddressViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string AddressTextBox_DisplayName {
            get {
                return ResourceManager.GetString("AddressTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddressTextBox_Hint {
            get {
                return ResourceManager.GetString("AddressTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rau dar adresa {0} este deja memorată..
        /// </summary>
        public static string AddressTextBox_InvalidDuplicateValue_Format {
            get {
                return ResourceManager.GetString("AddressTextBox_InvalidDuplicateValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți o adresă..
        /// </summary>
        public static string AddressTextBox_MissingValue {
            get {
                return ResourceManager.GetString("AddressTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string AddressToRemoveComboBox_DisplayName {
            get {
                return ResourceManager.GetString("AddressToRemoveComboBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doar adresele care nu sunt folosite pot fi șterse..
        /// </summary>
        public static string AddressToRemoveComboBox_Hint {
            get {
                return ResourceManager.GetString("AddressToRemoveComboBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renunță.
        /// </summary>
        public static string CancelButton_DisplayName {
            get {
                return ResourceManager.GetString("CancelButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renunță.
        /// </summary>
        public static string CancelButton_DisplayName1 {
            get {
                return ResourceManager.GetString("CancelButton_DisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge.
        /// </summary>
        public static string RemoveAddressButton_DisplayName {
            get {
                return ResourceManager.GetString("RemoveAddressButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ștergere stradă.
        /// </summary>
        public static string RemoveAddressViewTitle {
            get {
                return ResourceManager.GetString("RemoveAddressViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adrese neorganizate.
        /// </summary>
        public static string UngroupedAddressesLabel_DisplayName {
            get {
                return ResourceManager.GetString("UngroupedAddressesLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orice adresă neorganizată într-o zonă de livrare nu este inclusă în planificarea livrări comenzilor pentru acea adresă..
        /// </summary>
        public static string UngroupedAddressesLabel_Hint {
            get {
                return ResourceManager.GetString("UngroupedAddressesLabel_Hint", resourceCulture);
            }
        }
    }
}
