//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.Edesia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColourNamesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColourNamesStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrei15193.Edesia.Resources.ColourNamesStrings", typeof(ColourNamesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chihlimbar.
        /// </summary>
        public static string Amber {
            get {
                return ResourceManager.GetString("Amber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negru.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albastru.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maro.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt.
        /// </summary>
        public static string Cobalt {
            get {
                return ResourceManager.GetString("Cobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpuriu.
        /// </summary>
        public static string Crimson {
            get {
                return ResourceManager.GetString("Crimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cian.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Închis.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albastru închis.
        /// </summary>
        public static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maro închis.
        /// </summary>
        public static string DarkBrown {
            get {
                return ResourceManager.GetString("DarkBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt închis.
        /// </summary>
        public static string DarkCobalt {
            get {
                return ResourceManager.GetString("DarkCobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpuriu închis.
        /// </summary>
        public static string DarkCrimson {
            get {
                return ResourceManager.GetString("DarkCrimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cian închis.
        /// </summary>
        public static string DarkCyan {
            get {
                return ResourceManager.GetString("DarkCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smarald închis.
        /// </summary>
        public static string DarkEmerald {
            get {
                return ResourceManager.GetString("DarkEmerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai închis.
        /// </summary>
        public static string Darker {
            get {
                return ResourceManager.GetString("Darker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verde închis.
        /// </summary>
        public static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo închis.
        /// </summary>
        public static string DarkIndigo {
            get {
                return ResourceManager.GetString("DarkIndigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta închis.
        /// </summary>
        public static string DarkMagenta {
            get {
                return ResourceManager.GetString("DarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portocaliu închis.
        /// </summary>
        public static string DarkOrange {
            get {
                return ResourceManager.GetString("DarkOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roz închis.
        /// </summary>
        public static string DarkPink {
            get {
                return ResourceManager.GetString("DarkPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roșu închis.
        /// </summary>
        public static string DarkRed {
            get {
                return ResourceManager.GetString("DarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turcoaz închis.
        /// </summary>
        public static string DarkTeal {
            get {
                return ResourceManager.GetString("DarkTeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet închis.
        /// </summary>
        public static string DarkViolet {
            get {
                return ResourceManager.GetString("DarkViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smarald.
        /// </summary>
        public static string Emerald {
            get {
                return ResourceManager.GetString("Emerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gri.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gri închis.
        /// </summary>
        public static string GrayDark {
            get {
                return ResourceManager.GetString("GrayDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gri mai închis.
        /// </summary>
        public static string GrayDarker {
            get {
                return ResourceManager.GetString("GrayDarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gri deschis.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gri mai deschis.
        /// </summary>
        public static string GrayLighter {
            get {
                return ResourceManager.GetString("GrayLighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verde.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        public static string Indigo {
            get {
                return ResourceManager.GetString("Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albastru deschis.
        /// </summary>
        public static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albastru mai deschis.
        /// </summary>
        public static string LighterBlue {
            get {
                return ResourceManager.GetString("LighterBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verde deschis.
        /// </summary>
        public static string LightGreen {
            get {
                return ResourceManager.GetString("LightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oliv deschis.
        /// </summary>
        public static string LightOlive {
            get {
                return ResourceManager.GetString("LightOlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portocaliu deschis.
        /// </summary>
        public static string LightOrange {
            get {
                return ResourceManager.GetString("LightOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roz deschis.
        /// </summary>
        public static string LightPink {
            get {
                return ResourceManager.GetString("LightPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roșu deschis.
        /// </summary>
        public static string LightRed {
            get {
                return ResourceManager.GetString("LightRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turcoaz deschis.
        /// </summary>
        public static string LightTeal {
            get {
                return ResourceManager.GetString("LightTeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galben-Verzui.
        /// </summary>
        public static string Lime {
            get {
                return ResourceManager.GetString("Lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mov.
        /// </summary>
        public static string Mauve {
            get {
                return ResourceManager.GetString("Mauve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oliv.
        /// </summary>
        public static string Olive {
            get {
                return ResourceManager.GetString("Olive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portocaliu.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roz.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roșu.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argintiu.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafeniu.
        /// </summary>
        public static string Taupe {
            get {
                return ResourceManager.GetString("Taupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turcoaz.
        /// </summary>
        public static string Teal {
            get {
                return ResourceManager.GetString("Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        public static string Violet {
            get {
                return ResourceManager.GetString("Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alb.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galben.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
