//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.Edesia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeliveryZoneControllerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeliveryZoneControllerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrei15193.Edesia.Resources.DeliveryZoneControllerStrings", typeof(DeliveryZoneControllerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă.
        /// </summary>
        public static string AddDeliveryZoneButton_DisplayName {
            get {
                return ResourceManager.GetString("AddDeliveryZoneButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă zonă de livrare.
        /// </summary>
        public static string AddDeliveryZoneMenuItem_DisplayName {
            get {
                return ResourceManager.GetString("AddDeliveryZoneMenuItem_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugare zonă de livrare.
        /// </summary>
        public static string AddDeliveryZoneViewTitle {
            get {
                return ResourceManager.GetString("AddDeliveryZoneViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă stradă.
        /// </summary>
        public static string AddStreetMenuItem_DisplayName {
            get {
                return ResourceManager.GetString("AddStreetMenuItem_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Străzi incluse.
        /// </summary>
        public static string AvailableStreetsListBox_DisplayName {
            get {
                return ResourceManager.GetString("AvailableStreetsListBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvailableStreetsListBox_Hint {
            get {
                return ResourceManager.GetString("AvailableStreetsListBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renunță.
        /// </summary>
        public static string CancelButton_DisplayName {
            get {
                return ResourceManager.GetString("CancelButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone de livrare.
        /// </summary>
        public static string DefaultViewTitle {
            get {
                return ResourceManager.GetString("DefaultViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Această zonă de livrare nu conține străzi!.
        /// </summary>
        public static string DeliveryZoneAddressesListBox_NoValues {
            get {
                return ResourceManager.GetString("DeliveryZoneAddressesListBox_NoValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Această zonă nu are asociat un responsabil!.
        /// </summary>
        public static string DeliveryZoneAssigneeListBox_NoValues {
            get {
                return ResourceManager.GetString("DeliveryZoneAssigneeListBox_NoValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culoarea zonei de livrare.
        /// </summary>
        public static string DeliveryZoneColourComboBox_DisplayName {
            get {
                return ResourceManager.GetString("DeliveryZoneColourComboBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culoarea zonei de livrare este doar pentru a realiza o asociere vizuală cu destinația unui număr de livrări..
        /// </summary>
        public static string DeliveryZoneColourComboBox_Hint {
            get {
                return ResourceManager.GetString("DeliveryZoneColourComboBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culoarea trebuie introdusă în format hexazecimal (ex: #FA1519)..
        /// </summary>
        public static string DeliveryZoneColourTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("DeliveryZoneColourTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numele zonei de livrare.
        /// </summary>
        public static string DeliveryZoneLabel_DisplayName {
            get {
                return ResourceManager.GetString("DeliveryZoneLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona de livrare selectată nu există..
        /// </summary>
        public static string DeliveryZoneNameComboBox_InvalidValue {
            get {
                return ResourceManager.GetString("DeliveryZoneNameComboBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rau dar zona de livrare {0} este deja memorată..
        /// </summary>
        public static string DeliveryZoneNameTextBox_InvalidDuplicateValue_Format {
            get {
                return ResourceManager.GetString("DeliveryZoneNameTextBox_InvalidDuplicateValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numele zonei de livrare.
        /// </summary>
        public static string DeliveryZoneTextBox_DisplayName {
            get {
                return ResourceManager.GetString("DeliveryZoneTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to un nume unic pentru a referi zona de livrare.
        /// </summary>
        public static string DeliveryZoneTextBox_Hint {
            get {
                return ResourceManager.GetString("DeliveryZoneTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți numele zonei de livrare..
        /// </summary>
        public static string DeliveryZoneTextBox_MissingValue {
            get {
                return ResourceManager.GetString("DeliveryZoneTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifică.
        /// </summary>
        public static string EditDeliveryZoneButton_DisplayName {
            get {
                return ResourceManager.GetString("EditDeliveryZoneButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificare zonă de livrare.
        /// </summary>
        public static string EditDeliveryZoneViewTitle {
            get {
                return ResourceManager.GetString("EditDeliveryZoneViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsabilul zonei de livrare.
        /// </summary>
        public static string EmployeesComobBox_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesComobBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmployeesComobBox_Hint {
            get {
                return ResourceManager.GetString("EmployeesComobBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionează zone de livrare.
        /// </summary>
        public static string ManageDeliveryZonesButton_DisplayName {
            get {
                return ResourceManager.GetString("ManageDeliveryZonesButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă, modifică, șterge zone de livrare..
        /// </summary>
        public static string ManageDeliveryZonesButton_Hint {
            get {
                return ResourceManager.GetString("ManageDeliveryZonesButton_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge.
        /// </summary>
        public static string RemoveDeliveryZoneButton_DisplayName {
            get {
                return ResourceManager.GetString("RemoveDeliveryZoneButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ștergere zonă de livrare.
        /// </summary>
        public static string RemoveDeliveryZoneViewTitle {
            get {
                return ResourceManager.GetString("RemoveDeliveryZoneViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsabil: {1}, {0} (capacitate transport: {2}).
        /// </summary>
        public static string ResponsibleLabel_DisplayName_Format {
            get {
                return ResourceManager.GetString("ResponsibleLabel_DisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacitate transport:.
        /// </summary>
        public static string TransportCapacityLabel_DisplayName {
            get {
                return ResourceManager.GetString("TransportCapacityLabel_DisplayName", resourceCulture);
            }
        }
    }
}
