//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.Edesia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeliveryTaskControllerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeliveryTaskControllerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrei15193.Edesia.Resources.DeliveryTaskControllerStrings", typeof(DeliveryTaskControllerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la.
        /// </summary>
        public static string AtLabel_DisplayName {
            get {
                return ResourceManager.GetString("AtLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulează toate livrările.
        /// </summary>
        public static string CancelPendingDeliveriesButton_DisplayName {
            get {
                return ResourceManager.GetString("CancelPendingDeliveriesButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulează toate livrările indiferent dacă sunt planificate sau în execuție..
        /// </summary>
        public static string CancelPendingDeliveriesButton_Hint {
            get {
                return ResourceManager.GetString("CancelPendingDeliveriesButton_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulează livrare.
        /// </summary>
        public static string CancelPendingDeliveryButton_Hint {
            get {
                return ResourceManager.GetString("CancelPendingDeliveryButton_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizate.
        /// </summary>
        public static string CompletedTasksViewTitle {
            get {
                return ResourceManager.GetString("CompletedTasksViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizează.
        /// </summary>
        public static string CompleteTaskButton_DisplayName {
            get {
                return ResourceManager.GetString("CompleteTaskButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panoul cu sarcini.
        /// </summary>
        public static string DashboardViewTitle {
            get {
                return ResourceManager.GetString("DashboardViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livrarea.
        /// </summary>
        public static string DeliveryLabel_DisplayName {
            get {
                return ResourceManager.GetString("DeliveryLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stare livrare.
        /// </summary>
        public static string DeliveryStateLabel_DisplayName {
            get {
                return ResourceManager.GetString("DeliveryStateLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Începute.
        /// </summary>
        public static string InProgressTasksViewTitle {
            get {
                return ResourceManager.GetString("InProgressTasksViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comanda.
        /// </summary>
        public static string OrderLabel_DisplayName {
            get {
                return ResourceManager.GetString("OrderLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzi.
        /// </summary>
        public static string OrdersLabel_DisplayName {
            get {
                return ResourceManager.GetString("OrdersLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livrări în așteptare.
        /// </summary>
        public static string PendingDeliveriesLabel_DisplayName {
            get {
                return ResourceManager.GetString("PendingDeliveriesLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to În așteptare.
        /// </summary>
        public static string PendingTasksViewTitle {
            get {
                return ResourceManager.GetString("PendingTasksViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Începe.
        /// </summary>
        public static string StartTaskButton_DisplayName {
            get {
                return ResourceManager.GetString("StartTaskButton_DisplayName", resourceCulture);
            }
        }
    }
}
