//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.Edesia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrei15193.Edesia.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rau dar adresa {0} este deja memorată..
        /// </summary>
        public static string AddressTextBox_InvalidDuplicateValue_Format {
            get {
                return ResourceManager.GetString("AddressTextBox_InvalidDuplicateValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți o adresă..
        /// </summary>
        public static string AddressTextBox_MissingValue {
            get {
                return ResourceManager.GetString("AddressTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa de e-mail sau parola nu sunt valide..
        /// </summary>
        public static string CredentialControls_InvalidValues {
            get {
                return ResourceManager.GetString("CredentialControls_InvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Această zonă de livrare nu conține străzi!.
        /// </summary>
        public static string DeliveryZoneAddressesListBox_NoValues {
            get {
                return ResourceManager.GetString("DeliveryZoneAddressesListBox_NoValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Această zonă nu are asociat un responsabil!.
        /// </summary>
        public static string DeliveryZoneAssigneeListBox_NoValues {
            get {
                return ResourceManager.GetString("DeliveryZoneAssigneeListBox_NoValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culoarea trebuie introdusă în format hexazecimal (ex: #FA1519)..
        /// </summary>
        public static string DeliveryZoneColourTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("DeliveryZoneColourTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona de livrare selectată nu există..
        /// </summary>
        public static string DeliveryZoneNameComboBox_InvalidValue {
            get {
                return ResourceManager.GetString("DeliveryZoneNameComboBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rau dar zona de livrare {0} este deja memorată..
        /// </summary>
        public static string DeliveryZoneNameTextBox_InvalidDuplicateValue_Format {
            get {
                return ResourceManager.GetString("DeliveryZoneNameTextBox_InvalidDuplicateValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți numele zonei de livrare..
        /// </summary>
        public static string DeliveryZoneTextBox_MissingValue {
            get {
                return ResourceManager.GetString("DeliveryZoneTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rău dar adresa de e-mail {0} este deja folosită..
        /// </summary>
        public static string EMailTextBox_DuplicateValue_Format {
            get {
                return ResourceManager.GetString("EMailTextBox_DuplicateValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați introdus o adresă de e-mail validă..
        /// </summary>
        public static string EMailTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("EMailTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresele de e-mail trebuie să fie aceleași..
        /// </summary>
        public static string EMailTextBox_InvalidVerificationValue {
            get {
                return ResourceManager.GetString("EMailTextBox_InvalidVerificationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți o adresă de e-mail..
        /// </summary>
        public static string EMailTextBox_MissingValue {
            get {
                return ResourceManager.GetString("EMailTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați introdus un prenume corect..
        /// </summary>
        public static string FirstNameTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("FirstNameTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți un prenume..
        /// </summary>
        public static string FirstNameTextBox_MissingValue {
            get {
                return ResourceManager.GetString("FirstNameTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați introdus un nume corect..
        /// </summary>
        public static string LastNameTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("LastNameTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți un nume..
        /// </summary>
        public static string LastNameTextBox_MissingValue {
            get {
                return ResourceManager.GetString("LastNameTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolele trebuie să fie aceleași..
        /// </summary>
        public static string PasswordInput_InvalidVerificationValue {
            get {
                return ResourceManager.GetString("PasswordInput_InvalidVerificationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți o parolă..
        /// </summary>
        public static string PasswordInput_MissingValue {
            get {
                return ResourceManager.GetString("PasswordInput_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rău dar produsul {0} este deja existent..
        /// </summary>
        public static string ProductNameTextBox_DuplicateValue_Format {
            get {
                return ResourceManager.GetString("ProductNameTextBox_DuplicateValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți numele unui produs..
        /// </summary>
        public static string ProductNameTextBox_MissingValue {
            get {
                return ResourceManager.GetString("ProductNameTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să intorduceți un numar mai mare sau egal cu 0.00..
        /// </summary>
        public static string ProductPriceTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("ProductPriceTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți un preț..
        /// </summary>
        public static string ProductPriceTextBox_MissingValue {
            get {
                return ResourceManager.GetString("ProductPriceTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rău dar codul de înregistrare este prea vechi pentru a mai putea fi folosit. Trebuie sa vă reînregistrați..
        /// </summary>
        public static string RegistrationTokenInput_ExpiredValue {
            get {
                return ResourceManager.GetString("RegistrationTokenInput_ExpiredValue", resourceCulture);
            }
        }
    }
}
