//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.Edesia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ManageDeliveryZonesViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageDeliveryZonesViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrei15193.Edesia.Resources.ManageDeliveryZonesViewStrings", typeof(ManageDeliveryZonesViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă adresă.
        /// </summary>
        public static string AddAddressButton_DisplayName {
            get {
                return ResourceManager.GetString("AddAddressButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă zonă de livrare.
        /// </summary>
        public static string AddDeliveryZoneButton_DisplayName {
            get {
                return ResourceManager.GetString("AddDeliveryZoneButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înapoi la planificare livrări.
        /// </summary>
        public static string BackToDeliveryPlanningButton_DisplayName {
            get {
                return ResourceManager.GetString("BackToDeliveryPlanningButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone de livrare.
        /// </summary>
        public static string DeliveryZonesLabel_DisplayName {
            get {
                return ResourceManager.GetString("DeliveryZonesLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifică zonă de livrare.
        /// </summary>
        public static string EditDeliveryZoneButton_DisplayName {
            get {
                return ResourceManager.GetString("EditDeliveryZoneButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opțiuni pentru gestionare.
        /// </summary>
        public static string ManageOptionsLabel_DisplayName {
            get {
                return ResourceManager.GetString("ManageOptionsLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge adresă.
        /// </summary>
        public static string RemoveAddressButton_DisplayName {
            get {
                return ResourceManager.GetString("RemoveAddressButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge zonă de livrare.
        /// </summary>
        public static string RemoveDeliveryZoneButton_DisplayName {
            get {
                return ResourceManager.GetString("RemoveDeliveryZoneButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionare străzi și zone de livrare.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
    }
}
