//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.Edesia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderControllerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderControllerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrei15193.Edesia.Resources.OrderControllerStrings", typeof(OrderControllerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalii pentru adresa de livrare.
        /// </summary>
        public static string AddressDetailsTextBox_DisplayName {
            get {
                return ResourceManager.GetString("AddressDetailsTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numărul, bloc etc..
        /// </summary>
        public static string AddressDetailsTextBox_Hint {
            get {
                return ResourceManager.GetString("AddressDetailsTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să completați detalile adresei pentru livrare..
        /// </summary>
        public static string AddressDetailsTextBox_MissingValue {
            get {
                return ResourceManager.GetString("AddressDetailsTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înapoi.
        /// </summary>
        public static string BackToShoppingCart_DisplayName {
            get {
                return ResourceManager.GetString("BackToShoppingCart_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completare comandă.
        /// </summary>
        public static string CheckoutViewTitle {
            get {
                return ResourceManager.GetString("CheckoutViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzi în așteptare.
        /// </summary>
        public static string DefaultViewTitle {
            get {
                return ResourceManager.GetString("DefaultViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzi livrate.
        /// </summary>
        public static string DeliveredOrdersLabel_DisplayName {
            get {
                return ResourceManager.GetString("DeliveredOrdersLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa de livrare:.
        /// </summary>
        public static string DeliveryAddressLabel_DisplayName {
            get {
                return ResourceManager.GetString("DeliveryAddressLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalii livrare.
        /// </summary>
        public static string DeliveryDetailsLabel_DisplayName {
            get {
                return ResourceManager.GetString("DeliveryDetailsLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzi în curs de livrare.
        /// </summary>
        public static string EnRouteOrdersLabel_DisplayName {
            get {
                return ResourceManager.GetString("EnRouteOrdersLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comanda #{0}, {1:dd MMMM yyyy, HH:mm}.
        /// </summary>
        public static string OrderAccordionFrameHeader_DisplayName_Format {
            get {
                return ResourceManager.GetString("OrderAccordionFrameHeader_DisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalii produse.
        /// </summary>
        public static string OrderDetailsLabel_DisplayName {
            get {
                return ResourceManager.GetString("OrderDetailsLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} x {0}, {2:0.00} RON (total: {3:0.00} RON).
        /// </summary>
        public static string OrderedProductLabel_DisplayName_Format {
            get {
                return ResourceManager.GetString("OrderedProductLabel_DisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produse comandate.
        /// </summary>
        public static string OrderedProductsLabel_DisplayName {
            get {
                return ResourceManager.GetString("OrderedProductsLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comandă.
        /// </summary>
        public static string OrderLabel_DisplayName {
            get {
                return ResourceManager.GetString("OrderLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzi în așteptare.
        /// </summary>
        public static string PendingOrdersLabel_DisplayName {
            get {
                return ResourceManager.GetString("PendingOrdersLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preț individual.
        /// </summary>
        public static string PriceLabel_DisplayName {
            get {
                return ResourceManager.GetString("PriceLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantitate.
        /// </summary>
        public static string QuantityLabel_DisplayName {
            get {
                return ResourceManager.GetString("QuantityLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registru comenzi.
        /// </summary>
        public static string RegistryViewTitle {
            get {
                return ResourceManager.GetString("RegistryViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzi planificate.
        /// </summary>
        public static string ScheduledOrdersLabel_DisplayName {
            get {
                return ResourceManager.GetString("ScheduledOrdersLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programează comenzi.
        /// </summary>
        public static string SchedulePendingOrdersButton_DisplayName {
            get {
                return ResourceManager.GetString("SchedulePendingOrdersButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planifică manual comenzi pentru a fi livrate..
        /// </summary>
        public static string SchedulePendingOrdersButton_Hint {
            get {
                return ResourceManager.GetString("SchedulePendingOrdersButton_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strada pentru livrare.
        /// </summary>
        public static string SelectedStreetListBox_DisplayName {
            get {
                return ResourceManager.GetString("SelectedStreetListBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să alegeți o stradă pentru livrare..
        /// </summary>
        public static string SelectedStreetListBox_NoSelectedItem {
            get {
                return ResourceManager.GetString("SelectedStreetListBox_NoSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizează comandă.
        /// </summary>
        public static string SubmitOrderButton_DisplayName {
            get {
                return ResourceManager.GetString("SubmitOrderButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Andrei.
        /// </summary>
        public static string ThanksNoticeAuthor {
            get {
                return ResourceManager.GetString("ThanksNoticeAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulțumesc pentru timpul acordat realizării acestei comenzi, alături de altele realizate de alți utilizatori vor forma datele de test pentru motorul de planificare din spatele aplicației. Este foarte important ca aceste comenzi să fie cât mai apropiate de  comenzi reale pentru rezultate cât mai precise..
        /// </summary>
        public static string ThanksNoticeParagraph1 {
            get {
                return ResourceManager.GetString("ThanksNoticeParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulțumesc încă odata și spor în continuare!.
        /// </summary>
        public static string ThanksNoticeParagraph2 {
            get {
                return ResourceManager.GetString("ThanksNoticeParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preț total:.
        /// </summary>
        public static string TotalPriceLabel_DisplayName {
            get {
                return ResourceManager.GetString("TotalPriceLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total produse:.
        /// </summary>
        public static string TotalProductsLabel_DisplayName {
            get {
                return ResourceManager.GetString("TotalProductsLabel_DisplayName", resourceCulture);
            }
        }
    }
}
