//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.Edesia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductControllerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductControllerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrei15193.Edesia.Resources.ProductControllerStrings", typeof(ProductControllerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă.
        /// </summary>
        public static string AddProductButton_DisplayName {
            get {
                return ResourceManager.GetString("AddProductButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă produs.
        /// </summary>
        public static string AddProductMenuItem_DisplayName {
            get {
                return ResourceManager.GetString("AddProductMenuItem_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă produs.
        /// </summary>
        public static string AddProductViewTitle {
            get {
                return ResourceManager.GetString("AddProductViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă în coș.
        /// </summary>
        public static string AddToCartProductButton_Hint {
            get {
                return ResourceManager.GetString("AddToCartProductButton_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renunță.
        /// </summary>
        public static string CancelButton_DisplayName {
            get {
                return ResourceManager.GetString("CancelButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produse.
        /// </summary>
        public static string DefaultViewTitle {
            get {
                return ResourceManager.GetString("DefaultViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge produs.
        /// </summary>
        public static string DeleteProductButton_Hint {
            get {
                return ResourceManager.GetString("DeleteProductButton_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to „Edesia” este proiectul meu de licență. La suprafață este un magazin online, iar „în spate” este un motor de planificare. Sarcina principală a aplicației este să strângă comenzi folosind interfața web și să planifice sarcini pentru „angajați” (cum ar fi partiționarea comenzilor pe zone de livrare într-un mod optim)..
        /// </summary>
        public static string NoticeParagraph1 {
            get {
                return ResourceManager.GetString("NoticeParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Încă nu-i gata....
        /// </summary>
        public static string NoticeTitle {
            get {
                return ResourceManager.GetString("NoticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacitatea produsului.
        /// </summary>
        public static string ProductCapacityTextBox_DisplayName {
            get {
                return ResourceManager.GetString("ProductCapacityTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to un număr real mai mare decât 0.
        /// </summary>
        public static string ProductCapacityTextBox_Hint {
            get {
                return ResourceManager.GetString("ProductCapacityTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacitatea introdusă trebuie să fie un număr strict pozitiv..
        /// </summary>
        public static string ProductCapacityTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("ProductCapacityTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți capacitatea produsului..
        /// </summary>
        public static string ProductCapacityTextBox_MissingValue {
            get {
                return ResourceManager.GetString("ProductCapacityTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imaginea asociată produsului.
        /// </summary>
        public static string ProductImageTextBox_DisplayName {
            get {
                return ResourceManager.GetString("ProductImageTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductImageTextBox_Hint {
            get {
                return ResourceManager.GetString("ProductImageTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imaginea trebuie să fie .jpg, .jpeg, .gif sau .png..
        /// </summary>
        public static string ProductImageTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("ProductImageTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să funizați o imagine care să fie asociată produsului..
        /// </summary>
        public static string ProductImageTextBox_MissingValue {
            get {
                return ResourceManager.GetString("ProductImageTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numele produsului.
        /// </summary>
        public static string ProductNameTextBox_DisplayName {
            get {
                return ResourceManager.GetString("ProductNameTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rău dar produsul {0} este deja existent..
        /// </summary>
        public static string ProductNameTextBox_DuplicateValue_Format {
            get {
                return ResourceManager.GetString("ProductNameTextBox_DuplicateValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductNameTextBox_Hint {
            get {
                return ResourceManager.GetString("ProductNameTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți numele unui produs..
        /// </summary>
        public static string ProductNameTextBox_MissingValue {
            get {
                return ResourceManager.GetString("ProductNameTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prețul produsului (RON).
        /// </summary>
        public static string ProductPriceTextBox_DisplayName {
            get {
                return ResourceManager.GetString("ProductPriceTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to un număr real pozitiv cu maximum două zecimale.
        /// </summary>
        public static string ProductPriceTextBox_Hint {
            get {
                return ResourceManager.GetString("ProductPriceTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie sa introduceți un număr real pozitiv..
        /// </summary>
        public static string ProductPriceTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("ProductPriceTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți prețul produsului..
        /// </summary>
        public static string ProductPriceTextBox_MissingValue {
            get {
                return ResourceManager.GetString("ProductPriceTextBox_MissingValue", resourceCulture);
            }
        }
    }
}
