//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.Edesia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegisterViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrei15193.Edesia.Resources.RegisterViewStrings", typeof(RegisterViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa de E-Mail.
        /// </summary>
        public static string EMailTextBox_DisplayName {
            get {
                return ResourceManager.GetString("EMailTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rău dar adresa de e-mail {0} este deja folosită..
        /// </summary>
        public static string EMailTextBox_DuplicateValue_Format {
            get {
                return ResourceManager.GetString("EMailTextBox_DuplicateValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nume@exemplu.ro.
        /// </summary>
        public static string EMailTextBox_Hint {
            get {
                return ResourceManager.GetString("EMailTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați introdus o adresă de e-mail validă..
        /// </summary>
        public static string EMailTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("EMailTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresele de e-mail trebuie să fie aceleași..
        /// </summary>
        public static string EMailTextBox_InvalidVerificationValue {
            get {
                return ResourceManager.GetString("EMailTextBox_InvalidVerificationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți o adresă de e-mail..
        /// </summary>
        public static string EMailTextBox_MissingValue {
            get {
                return ResourceManager.GetString("EMailTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificați adresa de E-Mail.
        /// </summary>
        public static string EMailVerificationTextBox_DisplayName {
            get {
                return ResourceManager.GetString("EMailVerificationTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reintroduceți adresa de e-mail (verificare).
        /// </summary>
        public static string EMailVerificationTextBox_Hint {
            get {
                return ResourceManager.GetString("EMailVerificationTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenume.
        /// </summary>
        public static string FirstNameTextBox_DisplayName {
            get {
                return ResourceManager.GetString("FirstNameTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prenumele dumneavoastră.
        /// </summary>
        public static string FirstNameTextBox_Hint {
            get {
                return ResourceManager.GetString("FirstNameTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați introdus un prenume corect..
        /// </summary>
        public static string FirstNameTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("FirstNameTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți un prenume..
        /// </summary>
        public static string FirstNameTextBox_MissingValue {
            get {
                return ResourceManager.GetString("FirstNameTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume.
        /// </summary>
        public static string LastNameTextBox_DisplayName {
            get {
                return ResourceManager.GetString("LastNameTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numele dumneavoastră (de familie).
        /// </summary>
        public static string LastNameTextBox_Hint {
            get {
                return ResourceManager.GetString("LastNameTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați introdus un nume corect..
        /// </summary>
        public static string LastNameTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("LastNameTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți un nume..
        /// </summary>
        public static string LastNameTextBox_MissingValue {
            get {
                return ResourceManager.GetString("LastNameTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string PasswordInput_DisplayName {
            get {
                return ResourceManager.GetString("PasswordInput_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PasswordInput_Hint {
            get {
                return ResourceManager.GetString("PasswordInput_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolele trebuie să fie aceleași..
        /// </summary>
        public static string PasswordInput_InvalidVerificationValue {
            get {
                return ResourceManager.GetString("PasswordInput_InvalidVerificationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți o parolă..
        /// </summary>
        public static string PasswordInput_MissingValue {
            get {
                return ResourceManager.GetString("PasswordInput_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificați parola.
        /// </summary>
        public static string PasswordVerificationInput_DisplayName {
            get {
                return ResourceManager.GetString("PasswordVerificationInput_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reintroduceți parola (verificare).
        /// </summary>
        public static string PasswordVerificationInput_Hint {
            get {
                return ResourceManager.GetString("PasswordVerificationInput_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înregistrare.
        /// </summary>
        public static string RegisterButton_DisplayName {
            get {
                return ResourceManager.GetString("RegisterButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înregistrare.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
    }
}
