//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.Edesia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserControllerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserControllerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrei15193.Edesia.Resources.UserControllerStrings", typeof(UserControllerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa de e-mail sau parola nu sunt valide..
        /// </summary>
        public static string CredentialControls_InvalidValues {
            get {
                return ResourceManager.GetString("CredentialControls_InvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa de E-Mail.
        /// </summary>
        public static string EMailTextBox_DisplayName {
            get {
                return ResourceManager.GetString("EMailTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rău dar adresa de e-mail {0} este deja folosită..
        /// </summary>
        public static string EMailTextBox_DuplicateValue_Format {
            get {
                return ResourceManager.GetString("EMailTextBox_DuplicateValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nume@exemplu.ro.
        /// </summary>
        public static string EMailTextBox_Hint {
            get {
                return ResourceManager.GetString("EMailTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați introdus o adresă de e-mail validă..
        /// </summary>
        public static string EMailTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("EMailTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresele de e-mail trebuie să fie aceleași..
        /// </summary>
        public static string EMailTextBox_InvalidVerificationValue {
            get {
                return ResourceManager.GetString("EMailTextBox_InvalidVerificationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți o adresă de e-mail..
        /// </summary>
        public static string EMailTextBox_MissingValue {
            get {
                return ResourceManager.GetString("EMailTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificați adresa de E-Mail.
        /// </summary>
        public static string EMailVerificationTextBox_DisplayName {
            get {
                return ResourceManager.GetString("EMailVerificationTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reintroduceți adresa de e-mail (verificare).
        /// </summary>
        public static string EMailVerificationTextBox_Hint {
            get {
                return ResourceManager.GetString("EMailVerificationTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenume.
        /// </summary>
        public static string FirstNameTextBox_DisplayName {
            get {
                return ResourceManager.GetString("FirstNameTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prenumele dumneavoastră.
        /// </summary>
        public static string FirstNameTextBox_Hint {
            get {
                return ResourceManager.GetString("FirstNameTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați introdus un prenume corect..
        /// </summary>
        public static string FirstNameTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("FirstNameTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți un prenume..
        /// </summary>
        public static string FirstNameTextBox_MissingValue {
            get {
                return ResourceManager.GetString("FirstNameTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limba.
        /// </summary>
        public static string LanguageDropDown_DisplayName {
            get {
                return ResourceManager.GetString("LanguageDropDown_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume.
        /// </summary>
        public static string LastNameTextBox_DisplayName {
            get {
                return ResourceManager.GetString("LastNameTextBox_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numele dumneavoastră (de familie).
        /// </summary>
        public static string LastNameTextBox_Hint {
            get {
                return ResourceManager.GetString("LastNameTextBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați introdus un nume corect..
        /// </summary>
        public static string LastNameTextBox_InvalidValue {
            get {
                return ResourceManager.GetString("LastNameTextBox_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți un nume..
        /// </summary>
        public static string LastNameTextBox_MissingValue {
            get {
                return ResourceManager.GetString("LastNameTextBox_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentificare.
        /// </summary>
        public static string LoginButton_DisplayName {
            get {
                return ResourceManager.GetString("LoginButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentificare.
        /// </summary>
        public static string LoginMenuItemButton_DisplayName {
            get {
                return ResourceManager.GetString("LoginMenuItemButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentificare.
        /// </summary>
        public static string LoginViewTitle {
            get {
                return ResourceManager.GetString("LoginViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deconectare.
        /// </summary>
        public static string LogoutMenuItem_DisplayName {
            get {
                return ResourceManager.GetString("LogoutMenuItem_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string PasswordInput_DisplayName {
            get {
                return ResourceManager.GetString("PasswordInput_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PasswordInput_Hint {
            get {
                return ResourceManager.GetString("PasswordInput_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PasswordInput_Hint1 {
            get {
                return ResourceManager.GetString("PasswordInput_Hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolele trebuie să fie aceleași..
        /// </summary>
        public static string PasswordInput_InvalidVerificationValue {
            get {
                return ResourceManager.GetString("PasswordInput_InvalidVerificationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie să introduceți o parolă..
        /// </summary>
        public static string PasswordInput_MissingValue {
            get {
                return ResourceManager.GetString("PasswordInput_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificați parola.
        /// </summary>
        public static string PasswordVerificationInput_DisplayName {
            get {
                return ResourceManager.GetString("PasswordVerificationInput_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reintroduceți parola (verificare).
        /// </summary>
        public static string PasswordVerificationInput_Hint {
            get {
                return ResourceManager.GetString("PasswordVerificationInput_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;title&gt;Edesia - Înregistrare&lt;/title&gt;
        ///	&lt;style&gt;
        ///		body
        ///		{{
        ///			margin: 0;
        ///			color: #000000;
        ///			text-align: justify;
        ///			font-family: &apos;Segoe UI Light_&apos;, &apos;Open Sans Light&apos;, Verdana, Arial, Helvetica, sans-serif;
        ///			font-size: 10pt;
        ///		}}
        ///
        ///		h1
        ///		{{
        ///			margin: 0;
        ///			padding: 10px;
        ///			background-color: #008A00;
        ///			color: #FFFFFF;
        ///			font-size: 24pt;
        ///			font-weight: 300;
        ///		}}
        ///
        ///		a
        ///		{{
        ///			color: #60A917;
        ///			text-decoration: none;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Register_MailBody_Format {
            get {
                return ResourceManager.GetString("Register_MailBody_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveți cont? Înregistrațivă aici.
        /// </summary>
        public static string RegisterAccountButton_DisplayName {
            get {
                return ResourceManager.GetString("RegisterAccountButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înregistrare.
        /// </summary>
        public static string RegisterButton_DisplayName {
            get {
                return ResourceManager.GetString("RegisterButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înregistrare.
        /// </summary>
        public static string RegisterViewTitle {
            get {
                return ResourceManager.GetString("RegisterViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înregistrarea s-a încheiat cu succes. Vă puteți autentifica și începe să cumpărați!.
        /// </summary>
        public static string Registration_Completed_Paragraph1 {
            get {
                return ResourceManager.GetString("Registration_Completed_Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am trimis un e-mail la adresa oferită cu detalii despre următorii pași care trebuie urmați pentru a vă înregistra..
        /// </summary>
        public static string Registration_ConfirmationMailSent_Paragraph1 {
            get {
                return ResourceManager.GetString("Registration_ConfirmationMailSent_Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rău dar nu am putut finaliza crearea contului dumneavoastră deoarece s-a scurs timpul în care vă puteați confirma adresa de e-mail..
        /// </summary>
        public static string Registration_TokenExpired_Paragraph1 {
            get {
                return ResourceManager.GetString("Registration_TokenExpired_Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentru a vă crea cont trebuie să urmați pașii de înregistrare de la început..
        /// </summary>
        public static string Registration_TokenExpired_Paragraph2 {
            get {
                return ResourceManager.GetString("Registration_TokenExpired_Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pare rău dar codul de înregistrare este prea vechi pentru a mai putea fi folosit. Trebuie sa vă reînregistrați..
        /// </summary>
        public static string RegistrationTokenInput_ExpiredValue {
            get {
                return ResourceManager.GetString("RegistrationTokenInput_ExpiredValue", resourceCulture);
            }
        }
    }
}
